export const timezones = [
    "Etc/GMT+12",
    "Pacific/Midway",
    "Pacific/Honolulu",
    "US/Alaska",
    "America/Los_Angeles",
    "America/Tijuana",
    "US/Arizona",
    "America/Chihuahua",
    "US/Mountain",
    "America/Managua",
    "US/Central",
    "America/Mexico_City",
    "Canada/Saskatchewan",
    "America/Bogota",
    "US/Eastern",
    "US/East-Indiana",
    "Canada/Atlantic",
    "America/Caracas",
    "America/Manaus",
    "America/Santiago",
    "Canada/Newfoundland",
    "America/Sao_Paulo",
    "America/Argentina/Buenos_Aires",
    "America/Godthab",
    "America/Montevideo",
    "America/Noronha",
    "Atlantic/Cape_Verde",
    "Atlantic/Azores",
    "Africa/Casablanca",
    "Etc/Greenwich",
    "Europe/Amsterdam",
    "Europe/Belgrade",
    "Europe/Brussels",
    "Europe/Sarajevo",
    "Africa/Lagos",
    "Asia/Amman",
    "Europe/Athens",
    "Asia/Beirut",
    "Africa/Cairo",
    "Africa/Harare",
    "Europe/Helsinki",
    "Asia/Jerusalem",
    "Europe/Minsk",
    "Africa/Windhoek",
    "Asia/Kuwait",
    "Europe/Moscow",
    "Africa/Nairobi",
    "Asia/Tbilisi",
    "Asia/Tehran",
    "Asia/Muscat",
    "Asia/Baku",
    "Asia/Yerevan",
    "Asia/Kabul",
    "Asia/Yekaterinburg",
    "Asia/Karachi",
    "Asia/Calcutta",
    "Asia/Kathmandu",
    "Asia/Almaty",
    "Asia/Dhaka",
    "Asia/Rangoon",
    "Asia/Bangkok",
    "Asia/Krasnoyarsk",
    "Asia/Hong_Kong",
    "Asia/Kuala_Lumpur",
    "Asia/Irkutsk",
    "Asia/Taipei",
    "Australia/Perth",
    "Asia/Tokyo",
    "Asia/Seoul",
    "Asia/Yakutsk",
    "Australia/Adelaide",
    "Australia/Darwin",
    "Australia/Brisbane",
    "Australia/Canberra",
    "Australia/Guam",
    "Australia/Hobart",
    "Asia/Vladivostok",
    "Pacific/Port_Moresby",
    "Australia/Currie",
    "Pacific/Fiji",
    "Asia/Kamchatka",
    "Pacific/Auckland",
    "Pacific/Tongatapu",
    "Pacific/Apia"
];

export const currencies = [
    { code: "USD", name: "US Dollar ($)" },
    { code: "EUR", name: "Euro (€)" },
    { code: "GBP", name: "British Pound (£)" },
    { code: "INR", name: "Indian Rupee (₹)" },
    { code: "AED", name: "UAE Dirham (د.إ)" },
    { code: "CAD", name: "Canadian Dollar ($)" },
    { code: "AUD", name: "Australian Dollar ($)" },
    { code: "JPY", name: "Japanese Yen (¥)" },
    { code: "CNY", name: "Chinese Yuan (¥)" },
    { code: "SAR", name: "Saudi Riyal (﷼)" },
    { code: "BRL", name: "Brazilian Real (R$)" },
    { code: "MXN", name: "Mexican Peso ($)" },
    { code: "ZAR", name: "South African Rand (R)" },
    { code: "NGN", name: "Nigerian Naira (₦)" },
    { code: "KES", name: "Kenyan Shilling (KSh)" },
    { code: "EGP", name: "Egyptian Pound (E£)" },
    { code: "IDR", name: "Indonesian Rupiah (Rp)" },
    { code: "MYR", name: "Malaysian Ringgit (RM)" },
    { code: "PHP", name: "Philippine Peso (₱)" },
    { code: "SGD", name: "Singapore Dollar ($)" },
    { code: "THB", name: "Thai Baht (฿)" },
    { code: "VND", name: "Vietnamese Dong (₫)" },
];
